In [2]:
from pickletools import pylist

import numpy as np

arr_1d = np.array([1,2,3,4,5])
print("1-D Array: ", arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2-D Array: ", arr_2d)

1-D Array:  [1 2 3 4 5]
2-D Array:  [[1 2 3]
 [4 5 6]]


###List Vs Numpy

In [3]:
list1 = [1,2,3]
print("List Multiplication: ", list1*2)
np_arr = np.array([1,2,3])
print("Numpy Array: ", np_arr*2)

List Multiplication:  [1, 2, 3, 1, 2, 3]
Numpy Array:  [2 4 6]


In [6]:
import time
start = time.time()
pylist = [i*2 for i in range(100000000)]
print("List Time: ", time.time()-start)

start = time.time()
np_arr = np.arange(100000000)*2
print("Numpy Array Time: ", time.time()-start)

List Time:  2.324359893798828
Numpy Array Time:  0.2006087303161621


## creating array from scratch

In [13]:
zeros = np.zeros((3,4))
print("Zero's Array:\n",zeros)

ones = np.ones((3,4))
print("One Array:\n",ones)

full = np.full((3,4),7)
print("Full Array:\n",full)

random = np.random.random((3,4))
print("Random Array:\n",random)

seq = np.arange(0,12,1)
print("Sequence Array:\n",seq)

Zero's Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array:
 [[0.25091353 0.25826871 0.25406525 0.63226622]
 [0.53193635 0.78794817 0.26645571 0.98853175]
 [0.91473388 0.11951531 0.85028373 0.81709831]]
Sequence Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Vector, Matrices, Tensor

In [20]:
vector = np.array([1, 2, 3])
print("Vector Array:\n", vector)

matrices = np.array([[1,2,3],[4,5,6]])
print("Matrix Array:\n",matrices)

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])
print("Tensor Array:\n",tensor)

Vector Array:
 [1 2 3]
Matrix Array:
 [[1 2 3]
 [4 5 6]]
Tensor Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


## Array Properities

In [22]:
arr  = np.array([[1,2,3],
               [4,5,6]])
print("Shape: ", arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ", arr.size)
print("DType: ",arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


## Array Reshaping

In [34]:
arr = np.arange(12)
print("Original Array:\n",arr)

reshape = arr.reshape((3,4))
print("Reshaped Array:\n",reshape)

flat = reshape.flatten()
print("Flattened Array:" ,flat)

#ravel -> Return views, istead of copy
raveled = reshape.ravel()
print("Raveled Array:",raveled)

#Transpose
tran = reshape.T
print("Transposed Array:\n",tran)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
